### ISSUE TITLE
Enable and Disable Commands

### ISSUE THREAD

**Issue by Kyklas** [sampsyo/bkp1696#2]
On my BP Precision 1696 enable and disable command are reversed.

SOUT 0 turns the ouput on
SOUT 1 turns the output off

**Comment by sampsyo** [comment]
Huh, that's interesting. Is it the opposite of what's in the manual?

**Comment by Kyklas** [comment]
I check the following and it maches :
https://bkprecision.desk.com/customer/portal/kb_article_attachments/71714/original.pdf?1450722060

**Comment by sampsyo** [comment]
Right you are! I've reversed them.
